import { useState, useEffect } from 'react';
import { AlertTriangle, ShieldCheck } from 'lucide-react';

const MedicalDisclaimerModal = () => {
    const [isVisible, setIsVisible] = useState(false);

    useEffect(() => {
        const hasAccepted = localStorage.getItem('fuelflow_accepted_disclaimer');
        if (!hasAccepted) {
            setIsVisible(true);
        }
    }, []);

    const handleAccept = () => {
        localStorage.setItem('fuelflow_accepted_disclaimer', 'true');
        setIsVisible(false);
    };

    if (!isVisible) return null;

    return (
        <div style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.85)',
            backdropFilter: 'blur(8px)',
            zIndex: 99999,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px'
        }}>
            <div className="card animate-fadeIn" style={{
                maxWidth: '500px',
                width: '100%',
                maxHeight: '90vh',
                overflowY: 'auto',
                boxShadow: '0 24px 48px rgba(0,0,0,0.3)',
                padding: '32px'
            }}>
                <div style={{ textAlign: 'center', marginBottom: '24px' }}>
                    <div style={{ 
                        width: '72px', height: '72px', borderRadius: '50%', 
                        background: 'rgba(239, 68, 68, 0.1)', display: 'flex', 
                        alignItems: 'center', justifyContent: 'center', 
                        margin: '0 auto 16px', color: 'var(--danger-500)'
                    }}>
                        <AlertTriangle size={36} />
                    </div>
                    <h2 style={{ fontSize: '1.75rem', marginBottom: '8px', color: 'var(--text-primary)' }}>Important Medical Disclaimer</h2>
                    <p style={{ color: 'var(--text-secondary)' }}>Please read and accept before continuing.</p>
                </div>

                <div style={{ 
                    background: 'var(--bg-secondary)', 
                    padding: '20px', 
                    borderRadius: 'var(--radius-md)',
                    fontSize: '0.95rem',
                    lineHeight: 1.6,
                    color: 'var(--text-secondary)',
                    marginBottom: '24px',
                    border: '1px solid var(--glass-border)'
                }}>
                    <p style={{ marginBottom: '16px' }}>
                        <strong>Whittle Vitalio and its Digital Staff (AI Coach, Pastor, and Planners) are strictly for educational and informational purposes only.</strong>
                    </p>
                    <p style={{ marginBottom: '16px' }}>
                        This application is <strong>not a substitute for professional medical advice, diagnosis, or treatment.</strong> The AI recommendations are generated by language models and algorithms, which may sometimes produce generalized or inaccurate information.
                    </p>
                    <p style={{ marginBottom: '16px' }}>
                        Do not disregard or delay seeking professional medical advice because of information you have read on this application. Always consult with your physician, a registered dietitian, or another qualified healthcare provider before beginning any new diet, supplement routines, fasting protocol, or fitness program.
                    </p>
                    <p style={{ margin: 0 }}>
                        In a medical or spiritual emergency, please dial 911 or contact a crisis hotline immediately.
                    </p>
                </div>

                <button 
                    className="btn btn-primary btn-block btn-lg" 
                    onClick={handleAccept}
                    style={{ display: 'flex', justifyContent: 'center', gap: '8px', padding: '16px', fontSize: '1.1rem' }}
                >
                    <ShieldCheck size={24} />
                    I Understand and Agree
                </button>
            </div>
        </div>
    );
};

export default MedicalDisclaimerModal;
